# Generated by Django 2.0.7 on 2018-08-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180822_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='short_name',
            field=models.CharField(default='Unnamed topic', max_length=255),
        ),
    ]
