# Generated by Django 2.0.7 on 2018-10-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_topic_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='temperature_offset',
            field=models.FloatField(default=0),
        ),
    ]
